/* For human — bilingual (EN + TH) UI strings for the Redirect screen + its panels. The screen is
   self-contained, so it keeps its own label table instead of a shared i18n layer. {n}/{done}/{total}/
   {m} are filled at the call site. Keep EN and TH in sync when adding a key. */
export const T = {
  en: {
    kicker: "Migration · old site → new site", title: "URL Redirect Map",
    desc: "Map each old-site URL to its new-site target, verify both sides, then generate an IIS web.config to set up the 301 redirects.",
    verify: "Verify all", verifying: "Verifying…", cancel: "Cancel", add: "+ Row", importCsv: "Import CSV",
    webconfig: "web.config", exportCsv: "Export Excel", clear: "Clear",
    btnSave: "Save", btnLoad: "Load",
    saved: "Saved {n} rows (this browser)", loaded: "Loaded {n} rows",
    saveEmpty: "Nothing to save", loadEmpty: "No saved data", loadConfirm: "Replace the current table with the saved data?",
    exported: "Exported {n} rows to Excel", exportEmpty: "Nothing to export",
    cTotal: "Rows", cPending: "Pending", cDone: "Done", cProblem: "Problem", cSkip: "No redirect",
    hNo: "#", hSym: "Symbol", hOld: "Old URL", hNew: "New URL", hMatch: "Match", hCheck: "Check", hStatus: "Status", hNote: "Note", open: "Open in a new tab",
    notePh: "e.g. new URL has no page, path changed, awaiting target confirmation",
    emptyT: "No mappings yet", emptyS: "Discover from the old site's sitemap, or import the checklist CSV.",
    old: "old", neu: "new", already: "↪ already set", ready: "ready",
    opts: "web.config options", type: "Redirect", appendQs: "Keep query string", trailing: "Match trailing slash",
    importErr: "Could not read that CSV", verified: "Verified {n} rows", imported: "Imported {n} rows", wcDone: "Generated {n} rules" ,
    canceled: "Canceled", netErr: "Backend unreachable — is it running?", skipped: "{n} row(s) skipped (missing URL)",
    statusBlank: "— set status —", confirmClear: "Clear all rows?",
    // merged pull + compare panel (many old sites/URLs → one new site)
    discTitle: "Pull + compare URLs", discSym: "Symbol", discSymPh: "e.g. WHA-UP",
    discNew: "New site (base URL)", discNewPh: "e.g. https://www.example.com",
    discOldList: "Old sites / URLs (add several)", discAddOld: "+ add old",
    phSym: "e.g. ABC", phOld: "e.g. https://old.example.com", phNew: "e.g. https://www.example.com/page",
    discSitemap: "Sitemap URL (optional)", discSitemapPh: "default: <old base>/sitemap.xml",
    discBusy: "Pulling…", discRun: "Pull sitemaps + verify",
    discHint: "Pull the sitemap of EACH old site → match every page onto the one new site → verify. Each run REPLACES the table with the new results (the old rows are cleared).",
    discNeed: "No URLs found in the sitemap — check the old-site URL / sitemap", discDone: "Added {n} URLs from the sitemap", discNone: "No new URLs (already in the table)",
    discNeedAll: "Fill Symbol, the new base URL, and at least one old URL/site", reqStar: "required",
    discSitemapErr: "Could not read the sitemap — check the URL is reachable and valid XML",
    // HTTP Basic Auth — sites behind a browser "Sign in" dialog (often UAT)
    authTitle: "Sites that need a login (Basic Auth)",
    authHint: "Just run verify — any site that answers 401 is added here automatically; you only fill in username + password. Or add one yourself: the host is pre-filled from the URLs you typed above. Matched by host; stored in this browser only.",
    authHostPh: "host, e.g. site.uat.example.com", authUserPh: "username", authPassPh: "password", authAdd: "+ add login",
    foundLogin: "Verified {n} rows · found {m} site(s) that need a login — fill in username/password below, then verify again",
    foundLoginSitemap: "That sitemap needs a login (401/403) — added the site below; fill in username/password and run again",
    verifyProg: "Verifying {done}/{total}…", canceledAt: "Canceled at {done}/{total}",
    fOld: "old", fNew: "new",
    // per-row file + body check (filled by Verify) — table columns + their cell text
    hFiles: "Files", hBody: "Body",
    fNoFiles: "no files", fSame: "same ({n})", fDiff: "differ", fSpa: "WAF/JS",
    fGone: "missing on new", fAdded: "added on new",
    bodyHas: "has content", bodyEmpty: "empty", bodyH1Only: "H1 only", bodySpa: "WAF/JS — open in browser",
    // expandable per-page detail
    dtNone: "Verify first to see page details", dtDetails: "details",
    dtOld: "Old page", dtNew: "New page", dtFiles: "Files", dtVerdict: "Verdict",
    dtHttp: "HTTP", dtRedir: "→ redirects to", dtFinal: "→ final URL", dtReach: "· reachable",
    dtH1yes: "present", dtH1no: "none", dtThinFlag: "H1 only — empty body",
    candTitle: "Close matches", candChosen: "✓ chosen",
    dtCounts: "count", dtMatched: "on both", dtMissing: "missing on new", dtAdded: "added on new",
    dtAlready: "old already 301s to the new URL", dtFallback: "fallback target",
    dtNoUrl: "no URL on this side", dtContent: "Content",
    httpOk: "reachable", httpRedir: "redirect", httpErr: "error", httpDead: "unreachable",
    mRemove: "remove",
    // filter / sort bar over the table
    fltSearch: "Search URL, Symbol or note", fltAll: "All statuses", fltSort: "Sort",
    fltSeverity: "Problems first", fltMatch: "Lowest match first", fltOrder: "Table order",
    fltShowing: "Showing", fltClear: "Clear filter", fltNoMatch: "No rows match the filter",
    // deep-check (v0.2) issue filter — only shown once rows have been deep-verified
    fltIssueAll: "Deep check: any", fltIssueAny: "Has an issue", fltIssueFiles: "Files differ",
    fltIssueThin: "New page empty / thin", fltIssueError: "Error page", fltIssueLogin: "Needs login (401)",
  },
  th: {
    kicker: "ย้ายเว็บ · เว็บเดิม → เว็บใหม่", title: "URL Redirect Map",
    desc: "แมพ URL เว็บเดิมไปเว็บใหม่ทีละตัว ตรวจทั้งสองฝั่ง แล้ว gen ไฟล์ IIS web.config ไปตั้ง 301 redirect.",
    verify: "ตรวจทั้งหมด", verifying: "กำลังตรวจ…", cancel: "ยกเลิก", add: "+ แถว", importCsv: "นำเข้า CSV",
    webconfig: "web.config", exportCsv: "ส่งออก Excel", clear: "ล้าง",
    btnSave: "บันทึก", btnLoad: "โหลด",
    saved: "บันทึก {n} แถวแล้ว (ในเครื่องนี้)", loaded: "โหลด {n} แถวแล้ว",
    saveEmpty: "ไม่มีข้อมูลให้บันทึก", loadEmpty: "ไม่มีข้อมูลที่บันทึกไว้", loadConfirm: "แทนที่ตารางปัจจุบันด้วยข้อมูลที่บันทึกไว้?",
    exported: "ส่งออก {n} แถว เป็น Excel", exportEmpty: "ไม่มีข้อมูลให้ส่งออก",
    cTotal: "ทั้งหมด", cPending: "รอดำเนินการ", cDone: "ดำเนินการแล้ว", cProblem: "ติดปัญหา", cSkip: "ไม่ต้อง Redirect",
    hNo: "#", hSym: "Symbol", hOld: "URL เดิม", hNew: "URL ใหม่", hMatch: "ใกล้เคียง", hCheck: "ผลตรวจ", hStatus: "สถานะ", hNote: "Note", open: "เปิดลิงก์ (แท็บใหม่)",
    notePh: "เช่น URL ใหม่ยังไม่มีหน้า, Path เปลี่ยน, ต้องรอยืนยันปลายทาง",
    emptyT: "ยังไม่มี mapping", emptyS: "ดึงจาก sitemap เว็บเดิม หรือ นำเข้า CSV.",
    old: "เดิม", neu: "ใหม่", already: "↪ ตั้งแล้ว", ready: "พร้อม",
    opts: "ตัวเลือก web.config", type: "Redirect", appendQs: "เก็บ query string", trailing: "match ทั้งมี/ไม่มี /",
    importErr: "อ่าน CSV ไม่ได้", verified: "ตรวจแล้ว {n} แถว", imported: "นำเข้า {n} แถว", wcDone: "สร้าง {n} rule",
    canceled: "ยกเลิกแล้ว", netErr: "ต่อ backend ไม่ได้ — รันอยู่ไหม?", skipped: "ข้าม {n} แถว (URL ไม่ครบ)",
    statusBlank: "— เลือกสถานะ —", confirmClear: "ล้างทุกแถว?",
    // merged pull + compare panel (เว็บเก่าหลายเว็บ/URL → เว็บใหม่ 1 เว็บ)
    discTitle: "ดึง + เปรียบเทียบ URL", discSym: "Symbol", discSymPh: "เช่น WHA-UP",
    discNew: "เว็บใหม่ (base URL)", discNewPh: "ตัวอย่าง: https://www.example.com",
    discOldList: "เว็บเก่า / URL เก่า (เพิ่มได้หลายอัน)", discAddOld: "+ เพิ่มเว็บเก่า",
    phSym: "ตัวอย่าง: ABC", phOld: "ตัวอย่าง: https://old.example.com", phNew: "ตัวอย่าง: https://www.example.com/page",
    discSitemap: "Sitemap URL (ไม่บังคับ)", discSitemapPh: "ค่าเริ่มต้น: <เว็บเก่า>/sitemap.xml",
    discBusy: "กำลังดึง…", discRun: "ดึง sitemap + ตรวจ",
    discHint: "ดึง sitemap ของเว็บเก่าแต่ละเว็บ → จับคู่ทุกหน้าไปเว็บใหม่เว็บเดียว → ตรวจ. กดแต่ละครั้งจะล้างตารางเดิมแล้วแสดงผลรอบใหม่.",
    discNeed: "ไม่พบ URL จาก sitemap — ตรวจ URL เว็บเก่า/sitemap อีกที", discDone: "เพิ่ม {n} URL จาก sitemap", discNone: "ไม่มี URL ใหม่ (มีในตารางแล้ว)",
    discNeedAll: "กรอก Symbol, เว็บใหม่ (base URL) และ เว็บเก่า/URL เก่า อย่างน้อย 1", reqStar: "บังคับกรอก",
    discSitemapErr: "อ่าน sitemap ไม่ได้ — ตรวจว่า URL เข้าถึงได้และเป็น XML ที่ถูกต้อง",
    // HTTP Basic Auth — เว็บที่เด้ง dialog ให้ล็อกอิน (มักเป็น UAT)
    authTitle: "เว็บที่ต้องล็อกอิน (Basic Auth)",
    authHint: "แค่กดตรวจ — เว็บไหนตอบ 401 ระบบเพิ่ม host ให้อัตโนมัติ คุณแค่กรอก username/password. หรือกดเพิ่มเอง host จะดึงจาก URL ที่พิมพ์ไว้ด้านบนมาใส่ให้. จับคู่ด้วย host; เก็บในเบราว์เซอร์นี้เท่านั้น.",
    authHostPh: "host เช่น site.uat.example.com", authUserPh: "username", authPassPh: "password", authAdd: "+ เพิ่มล็อกอิน",
    foundLogin: "ตรวจแล้ว {n} แถว · พบ {m} เว็บที่ต้องล็อกอิน — กรอก username/password ด้านล่าง แล้วกดตรวจอีกครั้ง",
    foundLoginSitemap: "Sitemap ต้องล็อกอิน (401/403) — เพิ่มเว็บให้ด้านล่างแล้ว กรอก username/password แล้วกดใหม่",
    verifyProg: "กำลังตรวจ {done}/{total}…", canceledAt: "ยกเลิกที่ {done}/{total}",
    fOld: "เก่า", fNew: "ใหม่",
    // per-row file + body check (filled by Verify) — table columns + their cell text
    hFiles: "ไฟล์", hBody: "Body",
    fNoFiles: "ไม่มีไฟล์", fSame: "เหมือน ({n})", fDiff: "ต่างกัน", fSpa: "กันบอต/JS",
    fGone: "หายบนใหม่", fAdded: "เพิ่มบนใหม่",
    bodyHas: "มีเนื้อหา", bodyEmpty: "ว่าง", bodyH1Only: "H1 ลอย", bodySpa: "กันบอต/JS — เปิดในเบราว์เซอร์",
    // expandable per-page detail
    dtNone: "กด Verify ก่อนเพื่อดูรายละเอียดหน้า", dtDetails: "รายละเอียด",
    dtOld: "หน้าเก่า", dtNew: "หน้าใหม่", dtFiles: "ไฟล์", dtVerdict: "สรุป",
    dtHttp: "HTTP", dtRedir: "→ redirect ไป", dtFinal: "→ ปลายทางจริง", dtReach: "· เข้าถึงได้",
    dtH1yes: "มี", dtH1no: "ไม่มี", dtThinFlag: "มีแค่ H1 — body ว่าง",
    candTitle: "URL ใกล้เคียง", candChosen: "✓ เลือกไว้",
    dtCounts: "จำนวน", dtMatched: "มีทั้ง 2", dtMissing: "หายบนใหม่", dtAdded: "เพิ่มบนใหม่",
    dtAlready: "เก่า 301 ไปใหม่แล้ว", dtFallback: "ปลายทางสำรอง",
    dtNoUrl: "ฝั่งนี้ไม่มี URL", dtContent: "เนื้อหา",
    httpOk: "ใช้งานได้", httpRedir: "redirect", httpErr: "error", httpDead: "เข้าถึงไม่ได้",
    mRemove: "ลบ",
    // filter / sort bar over the table
    fltSearch: "ค้นหา URL, Symbol หรือ note", fltAll: "ทุกสถานะ", fltSort: "เรียง",
    fltSeverity: "ปัญหาก่อน (ไล่ระดับ)", fltMatch: "Match น้อยสุดก่อน", fltOrder: "ตามลำดับตาราง",
    fltShowing: "แสดง", fltClear: "ล้างตัวกรอง", fltNoMatch: "ไม่มีแถวตรงตัวกรอง",
    // ตัวกรองผลตรวจเชิงลึก (v0.2) — โชว์เมื่อมีแถวที่ตรวจ deep แล้ว
    fltIssueAll: "ผลตรวจเชิงลึก: ทั้งหมด", fltIssueAny: "มีปัญหา", fltIssueFiles: "ไฟล์ไม่ตรงกัน",
    fltIssueThin: "หน้าใหม่ว่าง/เนื้อหาน้อย", fltIssueError: "หน้าเป็น error", fltIssueLogin: "ต้องล็อกอิน (401)",
  },
};
