"""Generate an IIS URL-Rewrite web.config from redirect mapping rows.

The old WHA sites run on Azure App Service (Windows / IIS), so the chosen redirect mechanism
is an IIS **URL Rewrite** `web.config` dropped at the old site's web root. Each mapping row
becomes one rule: match the old URL's *path* and 301 (configurable) to the new absolute URL.

Pure string transform — no network, no state. Path → regex is anchored and regex-escaped so a
path like `/products/a.b` matches literally, not as a wildcard.
"""
from __future__ import annotations

import re
from urllib.parse import urlsplit
from xml.sax.saxutils import quoteattr

from ..schemas import WebConfigIn, WebConfigOut

# IIS action redirectType values (UI offers the common three; others pass through if valid)
_VALID_TYPES = {"Permanent", "Found", "SeeOther", "Temporary"}

_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by PiKaOs URL Redirect Map.
  Requires the IIS URL Rewrite module on the OLD site (Azure App Service / Windows has it).
  Place this file at the OLD site's web root as web.config. Each rule redirects one old path
  to its new absolute URL. Review before deploying; test a few paths after.
-->
<configuration>
  <system.webServer>
    <rewrite>
      <rules>
{rules}
      </rules>
    </rewrite>
  </system.webServer>
</configuration>
"""


def _old_path_pattern(old_url: str, match_trailing_slash: bool) -> str:
    """Build the rule's `match url` regex from the old URL's path. IIS matches the URL with the
    leading slash already stripped, so we strip it too, regex-escape, and anchor."""
    path = urlsplit(old_url.strip()).path or "/"
    rel = path.lstrip("/")
    if rel == "":
        return r"^$"                       # the site root
    esc = re.escape(rel).rstrip("/")       # slash isn't regex-special; rstrip avoids a double slash
    return rf"^{esc}/?$" if match_trailing_slash else rf"^{esc}$"


def _rule_name(symbol: str, old_url: str, idx: int, seen: set[str]) -> str:
    """A human-readable, collection-unique rule name (IIS requires names be unique)."""
    path = urlsplit(old_url.strip()).path or "/"
    label = f"{symbol} {path}".strip() if symbol else path
    base = f"redirect {idx} - {label}"
    name, n = base, 2
    while name in seen:
        name = f"{base} ({n})"
        n += 1
    seen.add(name)
    return name


def _rule_xml(name: str, pattern: str, new_url: str, redirect_type: str, append_qs: bool) -> str:
    # quoteattr returns the value wrapped in quotes with &, <, >, " escaped
    return (
        f"        <rule name={quoteattr(name)} stopProcessing=\"true\">\n"
        f"          <match url={quoteattr(pattern)} />\n"
        f"          <action type=\"Redirect\" url={quoteattr(new_url)} "
        f"redirectType=\"{redirect_type}\" appendQueryString=\"{str(append_qs).lower()}\" />\n"
        f"        </rule>"
    )


def generate(payload: WebConfigIn) -> WebConfigOut:
    redirect_type = payload.redirectType if payload.redirectType in _VALID_TYPES else "Permanent"
    rules: list[str] = []
    skipped: list[str] = []
    seen: set[str] = set()

    for idx, r in enumerate(payload.rows, 1):
        old, new = r.oldUrl.strip(), r.newUrl.strip()
        if not old or not new:
            skipped.append(f"{r.symbol or '?'}: {old or '(no old URL)'} → {new or '(no new URL)'}")
            continue
        pattern = _old_path_pattern(old, payload.matchTrailingSlash)
        name = _rule_name(r.symbol, old, idx, seen)
        rules.append(_rule_xml(name, pattern, new, redirect_type, payload.appendQueryString))

    xml = _TEMPLATE.format(rules="\n".join(rules))
    return WebConfigOut(xml=xml, ruleCount=len(rules), skipped=skipped)
